-- Translate common team names and abbreviations to Portuguese
-- This migration updates existing teams that were synced in English.

UPDATE teams SET name = 'Alemanha', short_name = 'ALE' WHERE name = 'Germany';
UPDATE teams SET name = 'Arábia Saudita', short_name = 'ARS' WHERE name = 'Saudi Arabia';
UPDATE teams SET name = 'Argentina', short_name = 'ARG' WHERE name = 'Argentina';
UPDATE teams SET name = 'Austrália', short_name = 'AUS' WHERE name = 'Australia';
UPDATE teams SET name = 'Bélgica', short_name = 'BEL' WHERE name = 'Belgium';
UPDATE teams SET name = 'Brasil', short_name = 'BRA' WHERE name = 'Brazil';
UPDATE teams SET name = 'Camarões', short_name = 'CAM' WHERE name = 'Cameroon';
UPDATE teams SET name = 'Canadá', short_name = 'CAN' WHERE name = 'Canada';
UPDATE teams SET name = 'Catar', short_name = 'CAT' WHERE name = 'Qatar';
UPDATE teams SET name = 'Coreia do Sul', short_name = 'COR' WHERE name = 'South Korea';
UPDATE teams SET name = 'Costa Rica', short_name = 'CRC' WHERE name = 'Costa Rica';
UPDATE teams SET name = 'Croácia', short_name = 'CRO' WHERE name = 'Croatia';
UPDATE teams SET name = 'Dinamarca', short_name = 'DIN' WHERE name = 'Denmark';
UPDATE teams SET name = 'Equador', short_name = 'EQU' WHERE name = 'Ecuador';
UPDATE teams SET name = 'Espanha', short_name = 'ESP' WHERE name = 'Spain';
UPDATE teams SET name = 'Estados Unidos', short_name = 'EUA' WHERE name = 'USA' OR name = 'United States';
UPDATE teams SET name = 'França', short_name = 'FRA' WHERE name = 'France';
UPDATE teams SET name = 'Gales', short_name = 'GAL' WHERE name = 'Wales';
UPDATE teams SET name = 'Gana', short_name = 'GAN' WHERE name = 'Ghana';
UPDATE teams SET name = 'Holanda', short_name = 'HOL' WHERE name = 'Netherlands';
UPDATE teams SET name = 'Inglaterra', short_name = 'ING' WHERE name = 'England';
UPDATE teams SET name = 'Irã', short_name = 'IRA' WHERE name = 'Iran';
UPDATE teams SET name = 'Itália', short_name = 'ITA' WHERE name = 'Italy';
UPDATE teams SET name = 'Japão', short_name = 'JAP' WHERE name = 'Japan';
UPDATE teams SET name = 'Marrocos', short_name = 'MAR' WHERE name = 'Morocco';
UPDATE teams SET name = 'México', short_name = 'MEX' WHERE name = 'Mexico';
UPDATE teams SET name = 'Polônia', short_name = 'POL' WHERE name = 'Poland';
UPDATE teams SET name = 'Portugal', short_name = 'POR' WHERE name = 'Portugal';
UPDATE teams SET name = 'Senegal', short_name = 'SEN' WHERE name = 'Senegal';
UPDATE teams SET name = 'Sérvia', short_name = 'SER' WHERE name = 'Serbia';
UPDATE teams SET name = 'Suíça', short_name = 'SUI' WHERE name = 'Switzerland';
UPDATE teams SET name = 'Tunísia', short_name = 'TUN' WHERE name = 'Tunisia';
UPDATE teams SET name = 'Uruguai', short_name = 'URU' WHERE name = 'Uruguay';
UPDATE teams SET name = 'Argélia', short_name = 'ALG' WHERE name = 'Algeria';
UPDATE teams SET name = 'Áustria', short_name = 'AUT' WHERE name = 'Austria';
UPDATE teams SET name = 'Bolívia', short_name = 'BOL' WHERE name = 'Bolivia';
UPDATE teams SET name = 'Chile', short_name = 'CHI' WHERE name = 'Chile';
UPDATE teams SET name = 'Colômbia', short_name = 'COL' WHERE name = 'Colombia';
UPDATE teams SET name = 'Costa do Marfim', short_name = 'CIV' WHERE name = 'Ivory Coast';
UPDATE teams SET name = 'Egito', short_name = 'EGI' WHERE name = 'Egypt';
UPDATE teams SET name = 'Grécia', short_name = 'GRE' WHERE name = 'Greece';
UPDATE teams SET name = 'Nigéria', short_name = 'NIG' WHERE name = 'Nigeria';
UPDATE teams SET name = 'Noruega', short_name = 'NOR' WHERE name = 'Norway';
UPDATE teams SET name = 'Paraguai', short_name = 'PAR' WHERE name = 'Paraguay';
UPDATE teams SET name = 'Peru', short_name = 'PER' WHERE name = 'Peru';
UPDATE teams SET name = 'República Tcheca', short_name = 'TCH' WHERE name = 'Czech Republic' OR name = 'Czechia';
UPDATE teams SET name = 'Suécia', short_name = 'SUE' WHERE name = 'Sweden';
UPDATE teams SET name = 'Turquia', short_name = 'TUR' WHERE name = 'Turkey';
UPDATE teams SET name = 'Ucrânia', short_name = 'UCR' WHERE name = 'Ukraine';
UPDATE teams SET name = 'Venezuela', short_name = 'VEN' WHERE name = 'Venezuela';
UPDATE teams SET name = 'África do Sul', short_name = 'AFS' WHERE name = 'South Africa';
UPDATE teams SET name = 'Bósnia e Herzegovina', short_name = 'BOS' WHERE name = 'Bosnia-Herzegovina';
UPDATE teams SET name = 'Cabo Verde', short_name = 'CAB' WHERE name = 'Cape Verde Islands';
UPDATE teams SET name = 'Nova Zelândia', short_name = 'NZL' WHERE name = 'New Zealand';
UPDATE teams SET name = 'Iraque', short_name = 'IRQ' WHERE name = 'Iraq';
UPDATE teams SET name = 'Jordânia', short_name = 'JOR' WHERE name = 'Jordan';
UPDATE teams SET name = 'RD Congo', short_name = 'CON' WHERE name = 'Congo DR';
UPDATE teams SET name = 'Uzbequistão', short_name = 'UZB' WHERE name = 'Uzbekistan';
UPDATE teams SET name = 'Panamá', short_name = 'PAN' WHERE name = 'Panama';
UPDATE teams SET name = 'Escócia', short_name = 'ESC' WHERE name = 'Scotland';
UPDATE teams SET name = 'Haiti', short_name = 'HAI' WHERE name = 'Haiti';
UPDATE teams SET name = 'Curaçao', short_name = 'CUR' WHERE name = 'Curaçao';
