name = "palpitae-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "palpitae"
database_id = "ffd7a7ed-3434-4db8-a505-b74c1cf79d6a" 

[vars]
BASE_URL = "http://localhost:8787"
FRONTEND_URL = "http://localhost:5173"
# Secrets — set via:
#   wrangler secret put JWT_SECRET
#   wrangler secret put GOOGLE_CLIENT_ID
#   wrangler secret put GOOGLE_CLIENT_SECRET
